name: GitHub Clone Count Update Everyday

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Parse latest clone count
        run: |
          curl -s --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/traffic/clones \
            > clone.json
          
          if grep -q "message" clone.json; then
            echo "Kritischer Fehler: Die GitHub-API hat einen Fehler zurückgegeben. Bitte überprüfe dein SECRET_TOKEN!"
            cat clone.json
            exit 1
          fi

      - name: Create or download Gist
        id: set_id
        env:
          GH_TOKEN: ${{ secrets.SECRET_TOKEN }}
          MY_GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          echo '{"count": 0, "uniques": 0, "clones": []}' > default_clone.json
          
          if [ -n "$MY_GIST_ID" ]; then
              echo "GIST_ID in den Secrets gefunden."
              echo "GIST=$MY_GIST_ID" >> $GITHUB_OUTPUT
              curl -s "https://githubusercontent.com{{ github.actor }}/$MY_GIST_ID/raw/clone.json" > clone_before.json
              
              if cat clone_before.json | grep -q '404: Not Found' || ! grep -q '"clones"' clone_before.json; then
                echo "Gist nicht mehr gültig oder leer. Erstelle neues Gist..."
                gist_id=$(gh gist create clone.json | awk -F / '{print $NF}')
                echo "$gist_id" | gh secret set GIST_ID
                echo "GIST=$gist_id" >> $GITHUB_OUTPUT
                cp default_clone.json clone_before.json
                rm -f CLONE.md
              fi
          else
              echo "Keine GIST_ID vorhanden. Erstelle ein neues Gist..."
              gist_id=$(gh gist create clone.json | awk -F / '{print $NF}')
              echo "$gist_id" | gh secret set GIST_ID
              echo "GIST=$gist_id" >> $GITHUB_OUTPUT
              cp default_clone.json clone_before.json
          fi

      - name: Update clone.json matrix
        run: |
          curl -s https://githubusercontent.com > main.py
          python3 main.py

      - name: Push updated data to Gist
        run: |
          content=$(sed -e 's/\\/\\\\/g' -e 's/\t/\\t/g' -e 's/\"/\\"/g' -e 's/\r//g' "clone.json" | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g')
          echo '{"description": "${{ github.repository }} clone statistics", "files": {"clone.json": {"content": "'"$content"'"}}}' > post_clone.json
          curl -s -X PATCH \
            --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @post_clone.json https://github.com{{ steps.set_id.outputs.GIST }} > /dev/null

      - name: Create CLONE.md file locally
        run: |
          if [ ! -f CLONE.md ]; then
            echo -e "**Markdown**\n\n\`\`\`markdown\n[![GitHub Clones](https://img.shields.io/badge/dynamic/json?color=success&label=Clone&query=count&url=https://githubusercontent.com{{ github.actor }}/${{ steps.set_id.outputs.GIST }}/raw/clone.json&logo=github)](https://github.com)\n\`\`\`" > CLONE.md
          fi

      - name: Commit and Push Markdown Badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f CLONE.md ] && git status --porcelain | grep -q CLONE.md; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@://github.com"
            git add CLONE.md
            git commit -m "chore: create clone count badge file"
            git push origin HEAD:${{ github.ref }}
          fi
